[WIP][Improve]Flutter のバージョンを 3.19.3 に更新
yumemi-inc/flutter-mobile-project-template pull request #167
Opened 2024-03-18 07:03 UTC by trm11tkr

## 概要

close: #151 

## レビュー観点
- アプリが適切に動作するか
- 環境分け対応の修正で考慮漏れがないか

## レビューレベル

- [ ] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [x] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [x] 数日以内で見てもらいたい 🐢

## 画像 / 動画

- 見た目に関する変更がないため省略します

## 動作確認手順
下記コマンドを実行して、使用する Flutter のバージョンを更新してください。
```shell
fvm use
```

## 備考
参考; https://github.com/flutter/flutter/issues/139289#issuecomment-1954103555

2024-03-18 07:09 UTC, trm11tkr commented on apps/app/ios/Flutter/AppFrameworkInfo.plist
> +  <string>12.0</string>
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
3.19.1 から iOS 11 は非推奨になリました。
ref: https://medium.com/flutter/whats-new-in-flutter-3-19-58b1aae242d2#:~:text=for%20full%20details.-,Deprecate%20iOS%2011,-Due%20to%20a

2024-03-22 01:13 UTC, trm11tkr commented
@tatsutakein @iseruuuuu 
お手隙の際にレビューよろしくお願いします🙏

2024-03-22 01:47 UTC, blendthink requested changes
@trm11tkr 
Android の Gradle の部分がいくつか更新されたようですので、ご確認お願いします 🙏 
https://github.com/blendthink/flutter-mobile-template-diff/pull/12/files

2024-03-22 06:35 UTC, trm11tkr commented
@blendthink 
> Android の Gradle の部分がいくつか更新されたようですので、ご確認お願いします 🙏

ご指摘いただきありがとうございます！
[2a32aca](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/167/commits/2a32acaba39131383cbf4602cefe309e985ccdea) にて対応いたしました。

2024-03-22 06:40 UTC, blendthink reviewed
@trm11tkr 
新たに一点コメントさせていただきましたのでご確認お願いします 🙏

2024-03-22 06:40 UTC, blendthink commented on .fvm/fvm_config.json
> +  "flutterSdkVersion": "3.19.3",
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
Flutter のバージョンを更新したことによって、ルート・アプリ・パッケージごとの pubspec.yaml や melos.yaml を更新しておくほうが好ましいと思いますので修正お願いします 🙏 

- https://github.com/yumemi-inc/flutter-mobile-project-template/blob/2a32acaba39131383cbf4602cefe309e985ccdea/pubspec.yaml#L4
- https://github.com/yumemi-inc/flutter-mobile-project-template/blob/2a32acaba39131383cbf4602cefe309e985ccdea/melos.yaml#L12-L13

2024-03-22 07:23 UTC, trm11tkr commented on .fvm/fvm_config.json
> +  "flutterSdkVersion": "3.19.3",
@blendthink 
[yumemi_llints 1.7.0](https://pub.dev/packages/yumemi_lints) (最新)が [flutter 3.19.0](https://github.com/yumemi-inc/flutter-yumemi-lints/tree/1.7.0/lib/flutter/3.19.0) までしか対応しておりませんでした…！

yumemi_lints 2.0.0 のリリース後の対応となりますかね…！

2024-03-22 07:25 UTC, blendthink commented on .fvm/fvm_config.json
> +  "flutterSdkVersion": "3.19.3",
@trm11tkr 
いったん yumemi_lints は無視して進めてしまってもいいかなと思います、、！

2024-03-22 07:46 UTC, trm11tkr commented on .fvm/fvm_config.json
> +  "flutterSdkVersion": "3.19.3",
@blendthink 

以下で対応いたしました。
Dart version update: [36480c1](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/167/commits/36480c12cb0929bab58b1207ec01a1f341b9dae8)
Flutter version update: [9cef494](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/167/commits/9cef4942160be24879a9b9c8b9b720d5994bfba9)

yumemi_lints の件は、Issue を作成しておきました！(#170 )

2024-03-22 07:48 UTC, blendthink approved these changes
Issue 作成までご対応いただきありがとうございます！
LGTM です！
![LGTM](https://image.lgtmoon.dev/241447)

2024-03-22 07:49 UTC, trm11tkr commented
レビューいただきありがとうございます！
マージさせていただきます！

2024-03-22 07:55 UTC, merged