Feature/flutter update 3 22
yumemi-inc/flutter-mobile-project-template pull request #208
Opened 2024-05-17 10:27 UTC by Yamasaki-pan961

## 概要

## レビュー観点

## レビューレベル

- [ ] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [ ] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [ ] 数日以内で見てもらいたい 🐢

## 画像 / 動画

|           Before           |           After            |           Design           |
|:--------------------------:|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> | <img src="" width="300" /> |

## 動作確認手順

## 備考

2024-05-28 06:45 UTC, Aosanori commented on melos.yaml
>        freezed_annotation: ^2.4.1
本PRとは関係なくて申し訳ございませんが、こちらアルファベット順に直していただきたいです。
```yaml
dependencies:
      flutter_hooks: ^0.20.5
      flutter_riverpod: ^2.5.1
      freezed_annotation: ^2.4.1
      hooks_riverpod: ^2.5.1
      intl: ^0.19.0
      json_annotation: ^4.8.1
      riverpod_annotation: ^2.3.5
```

2024-05-28 06:47 UTC, Aosanori commented
@Yamasaki-pan961 
動作に関しては問題ないと思います！

2024-05-28 06:49 UTC, Aosanori reviewed
ざっと確認いたしましたが、コードレビュー初心者であることと、このPJでは新参者であるため、他の方のレビューもいただけるといいかなという状態です 🙇

2024-05-28 08:37 UTC, blendthink requested changes
@Yamasaki-pan961 
いくつかコメントしましたので、ご対応お願いします 🙏 
また、 Gradle の更新もしておきたいです。

案件情報の兼ね合いで詳しくは Slack でやり取りさせてください、、！

2024-05-28 08:37 UTC, blendthink commented on apps/app/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
このタイミングなので 3.22.1 にしたいです！（あと、バージョンの記載がおかしいようです 🙏 ）
```suggestion
  sdk: ^3.4.1
  flutter: ^3.22.1
```

2024-05-28 08:37 UTC, blendthink commented on apps/catalog/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on melos.yaml
> +      flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/cores/core/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/cores/data/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/cores/designsystem/lib/src/themes/color_schemes.dart
> +  surfaceContainerHighest: Color(0xFF42474D),
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
まだ ↓ で自動生成して出力したファイルには反映されていないよう。。
https://m3.material.io/theme-builder#/custom

![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
上記の旨を、ファイルの上部のコメントのあたりに記載お願いします 🙏

2024-05-28 08:37 UTC, blendthink commented on packages/cores/designsystem/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/cores/init/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/cores/navigation/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/features/debug_mode/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/features/github_repository/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/features/setting/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on packages/features/webview/pubspec.yaml
> +  flutter: ^3.20.0
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同じく

2024-05-28 08:37 UTC, blendthink commented on .fvmrc
> +  "flutter": "3.22.0",
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
このタイミングなので 3.22.1 に更新お願いします！
```suggestion
  "flutter": "3.22.1",
```

2024-05-28 11:13 UTC, blendthink commented
こちら @ Yamasaki-pan961 さんとお話して、 @blendthink が引き継ぐことになりました、、！

2024-05-29 11:32 UTC, morikann submitted a review, later dismissed
LGTM です！

📝 mason で作成するパッケージの dart, flutter バージョンは hooks で自動更新されるため、わざわざ更新していない認識です。

2024-05-29 11:39 UTC, blendthink commented
レビューありがとうございます！

> 📝 mason で作成するパッケージの dart, flutter バージョンは hooks で自動更新されるため、わざわざ更新していない認識です。

あー、ただ、少し気持ち悪いのでさくっと修正しちゃいましょうかね　 🙏

2024-05-29 11:46 UTC, blendthink commented
↓で対応して、ローカルで動作確認できたので、CI 通ったらマージさせていただきます！
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/208/commits/7ade4143e71d8a4e01fa5abbc806abb159e41788

2024-05-29 11:46 UTC, blendthink approved these changes

2024-05-29 12:12 UTC, morikann approved these changes

2024-05-29 12:12 UTC, merged