Docs/issue 177 add flutter upgrade document
yumemi-inc/flutter-mobile-project-template pull request #241
Opened 2024-06-05 08:35 UTC by mqkotoo

## 概要

#177 対応

## レビュー観点

## レビューレベル

- [ ] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [ ] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [ ] 数日以内で見てもらいたい 🐢

## 画像 / 動画

|           Before           |           After            |           Design           |
|:--------------------------:|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> | <img src="" width="300" /> |

## 動作確認手順

## 備考

2024-06-05 10:20 UTC, K9i-0 requested changes
これ対応終わったらみるのでRequest Chnagesしておきます
https://yumemi.slack.com/archives/C0585H2BG9L/p1717581384257339

2024-06-10 08:11 UTC, K9i-0 requested changes

2024-06-10 08:11 UTC, K9i-0 commented on docs/ja/UPGRADE_FLUTTER.md
> +2. `pubspec.yaml` の `sdk, flutter` 部分のバージョンを更新
マルチパッケージでpubspec.yamlは複数あるので、どのpubspec.yamlか書いて欲しいです。
あとこのタイミングで更新が必要なルートのpubspec.yamlはsdkしか書いてないです。

2024-06-10 23:51 UTC, mqkotoo commented on docs/ja/UPGRADE_FLUTTER.md
> +2. `pubspec.yaml` の `sdk, flutter` 部分のバージョンを更新
ありがとうございます、修正します

2024-06-11 00:46 UTC, K9i-0 approved these changes
LGTM

2024-06-11 00:46 UTC, merged