chore(mason): feature 系のパッケージ作成の mason brick を追加
yumemi-inc/flutter-mobile-project-template pull request #248
Opened 2024-06-11 11:26 UTC by tatsutakein

## 概要

- close: #202 

feature 系のパッケージ作成の mason brick を追加します。

`foo_bar` という名前で feature パッケージを作成する場合、以下のような構成で作成される想定です。

```text
./packages/features/foo_bar/
├── README.md
├── analysis_options.yaml
├── build.yaml
├── l10n.yaml
├── lib
│   ├── l10n.dart
│   ├── src
│   │   ├── gen
│   │   │   └── l10n
│   │   │       ├── l10n.dart
│   │   │       ├── l10n_en.dart
│   │   │       └── l10n_ja.dart
│   │   ├── l10n
│   │   │   ├── features_foo_bar_en.arb
│   │   │   └── features_foo_bar_ja.arb
│   │   └── ui
│   │       ├── components
│   │       │   └── foo_bar_text.dart
│   │       └── pages
│   │           ├── bar
│   │           │   ├── bar_page.dart
│   │           │   └── components
│   │           │       └── bar_text.dart
│   │           └── foo
│   │               ├── components
│   │               │   └── foo_text.dart
│   │               └── foo_page.dart
│   └── ui.dart
├── pubspec.lock
├── pubspec.yaml
└── test
    └── foo_bar_test.dart
```

## レビュー観点

- 生成される内容に過不足がないか

## レビューレベル

- [x] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [ ] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [x] 数日以内で見てもらいたい 🐢

## 画像 / 動画

<img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/19267812/f6b93abf-588b-4b02-b5bf-43f44bbbdac1" />

## 確認したこと

- [x] `mason get` と `mason make features_package` 実行後、apps/app 側でルートや L10n 設定等をしたうえでページ遷移できること（Android）

## 動作確認手順

1. `mason get` を実行
2. `mason make features_package` を実行し、パッケージが生成されることを確認
3. （念入りに動作確認する場合）apps/app 側に追加した feature パッケージ依存の追加し、ルートや L10n 設定等をしてページ遷移できることを確認

## 備考

2024-06-12 02:56 UTC, tatsutakein commented on tools/bricks/features_package/__brick__/packages/features/{{feature_name.snakeCase()}}/.gitignore
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

既存の features/github_repository パッケージのものを流用しています。

https://github.com/yumemi-inc/flutter-mobile-project-template/blob/4cb8b82d7c4707ac55ad5b692e1873a4de996e9a/packages/features/github_repository/.gitignore#L1-L32

2024-06-12 02:57 UTC, tatsutakein commented on tools/bricks/features_package/__brick__/packages/features/{{feature_name.snakeCase()}}/build.yaml
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

既存の features/github_repository パッケージのものを流用しています。

https://github.com/yumemi-inc/flutter-mobile-project-template/blob/4cb8b82d7c4707ac55ad5b692e1873a4de996e9a/packages/features/github_repository/build.yaml#L1-L27

2024-06-12 06:38 UTC, K9i-0 requested changes
Slackに気になったこと書きました 🙆‍♂️ 
https://yumemi.slack.com/archives/C0585H2BG9L/p1718174271913189?thread_ts=1718109101.023699&cid=C0585H2BG9L

2024-06-14 05:11 UTC, tatsutakein commented
@K9i-0 
いただいたフィードバックを元に修正いたしました 🙆

2024-06-15 09:06 UTC, K9i-0 approved these changes
LGTM

2024-06-15 09:06 UTC, merged