feat(samples): github repository のサンプルアプリパッケージを追加
yumemi-inc/flutter-mobile-project-template pull request #295
Opened 2024-07-30 08:27 UTC by tatsutakein

## 概要

- #275 

github repository のサンプルアプリパッケージを追加します。
変更ファイル数が多くなってしまうため一旦はパッケージの追加のみとし、実装は別 PR とする予定です。

## レビュー観点

## レビューレベル

- [x] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [ ] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [x] 数日以内で見てもらいたい 🐢

## 画像 / 動画

|           Before           |           After            |           Design           |
|:--------------------------:|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> | <img src="" width="300" /> |

## 確認したこと

## 動作確認手順

## 備考

2024-07-30 09:09 UTC, tatsutakein commented on .github/labeler.yml
> +
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

melos bs 時に生成されています。

2024-07-30 09:09 UTC, tatsutakein commented on melos.yaml
> +  - samples/*
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

新しく sample ディレクトリを認知するよう追加しています。

2024-07-30 09:17 UTC, blendthink approved these changes
LGTM です！

サンプルアプリの実装をする際に IDE の起動設定ファイルの変更もあわせて対応したいですね、、！ 他のサンプルが増えたときにコマンドが多くなりすぎないように、できれば VS Code は input をうまく活用したいかも？（ IntelliJ では難しい？）

2024-07-30 09:39 UTC, blendthink requested changes
📝 Slack のハドルでのお話メモ

- Android・iOS アプリは削除して Web アプリだけにする
- IDE の設定ファイルの更新をする（ input などの対応はしない）

2024-07-31 03:36 UTC, tatsutakein commented
@blendthink 
ハドルでお話した改善点について、対応してみました！
お手数ですが、再度ご確認いただけますと幸いです 🙏

2024-07-31 04:07 UTC, blendthink approved these changes
LGTM です！
ご対応ありがとうございます！

2024-07-31 05:24 UTC, tatsutakein commented
丁寧にご確認いただきありがとうございました！
マージいたします 🙆

2024-07-31 05:25 UTC, merged