多言語対応
yumemi-inc/flutter-mobile-project-template pull request #48
Opened 2024-01-10 07:27 UTC by iseruuuuu

## 概要

- 多言語対応を行いました。
- マルチパッケージ構成でも使いやすいようにする対応は別PRで実装予定です。

- close #3 

### タスク
- [x] 多言語対応に必要なPackageの追加する。
- [x] arbファイルを日本語と英語の２種類作成する。
- [x] l10n.yamlに必要なコードを記載する。
- [x] コード生成を行う。
- [x] `MaterialApp`に必要な記載を行う。
- [x] main.dartとは別のファイル（HomeScreen）のAppBarにタイトルを仮で追記する 。

### レビューする上で伝えておきたいこと
- MaterialApp直下に入れると、AppLocalizationsの初期化完了前に呼び出されるため、Nullでエラーが発生するそうだったので、仮で`HomeScreen`を追加して、そちらに記載しました。もし、他にいい書き方があれば、コメントいただけると幸いです！
ソース：https://github.com/orgs/yumemi-inc/projects/8/views/1?pane=issue&itemId=47955129
- `l10n.yaml`の記載内容は、以下のIssuesを参考にしました。
ソース：https://github.com/orgs/yumemi-inc/projects/8/views/1?pane=issue&itemId=47955129

## レビュー観点

## レビューレベル

- [ ] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [x] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [x] 数日以内で見てもらいたい 🐢

## 画像 / 動画

|           日本語設定           |           英語設定           |       
|:--------------------------:|:--------------------------:|
| <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/67954894/1b753857-ce0a-450f-a9d5-2643e545a541" width="300" /> | <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/67954894/54ea6740-5cb8-4f1e-83d5-4adf376adc57" width="300" /> | 

## 動作確認手順

## 備考

2024-01-10 07:44 UTC, iseruuuuu commented
@tatsutakein @trm11tkr 
お手隙の際にレビューお願いします！

2024-01-10 07:46 UTC, iseruuuuu commented on apps/app/lib/gen/l10n/l10n.dart
> +}
生成されたコードは` .gitattributes`に記載してもいいかなと思いましたが、ご意見をいただける幸いです🙇

2024-01-11 03:40 UTC, tatsutakein reviewed
自動生成系のコードについて議論しておきたいですね 👌

2024-01-11 03:40 UTC, tatsutakein commented on apps/app/lib/gen/l10n/l10n.dart
> +}
個人的な好みでいうと ignore したい派ですが、こちらはチームメンバーで認識統一できたほうが良さそうなので他の方のご意見も伺いたいですね 👀

2024-01-11 03:51 UTC, Yamasaki-pan961 commented on apps/app/lib/gen/l10n/l10n.dart
> +}
生成されるコードを`.gitattributes`で指定することでレビューの負荷が下がって良いと思いました。👍

個人的には`ignore`にしない方がローカルでの生成コストが下げられて良いかなと思いました。
以下のissueにあるように最新の生成ファイルがPRに反映されているかのCIが組まれる予定っぽいので`ignore`にしない方向なのかなと思ってました！
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/20

2024-01-11 03:57 UTC, tatsutakein commented on apps/app/lib/gen/l10n/l10n.dart
> +}
あ、すみません少し勘違いしていました。。
生成ファイルの Git 管理自体は行う前提でしたね 🙇

`.gitattributes` への指定は自分も有りだと思いました 🙆

2024-01-11 04:13 UTC, iseruuuuu commented on apps/app/lib/gen/l10n/l10n.dart
> +}
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/48#discussion_r1448261394
僕も山﨑さんと同じ意見で、`.gitattributes`が一番可読性もよく、生成コストも下がるかなと考えています〜！

2024-01-11 04:36 UTC, iseruuuuu commented on apps/app/lib/gen/l10n/l10n.dart
> +}
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/48/commits/fd8e887c2f857997bab0a810706d979b273b8b40
こちらのCommitで`.gitattributes`の追記を行いました！

2024-01-11 04:53 UTC, tatsutakein requested changes
@iseruuuuu 
一点確認と修正をお願いいたします 🙏

2024-01-11 04:53 UTC, tatsutakein commented on .gitattributes
> +l10n._ja.dart linguist-generated=true
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

不要な `.` が混ざっている気がします 👀

```suggestion
l10n_ja.dart linguist-generated=true
```

2024-01-11 05:20 UTC, iseruuuuu commented on .gitattributes
> +l10n._ja.dart linguist-generated=true
教えていただきありがとうございます🙇
こちらで修正してみました！
df55120

2024-01-11 06:23 UTC, tatsutakein approved these changes
ご対応いただきありがとうございました！
LGTM です 👍

2024-01-11 07:38 UTC, iseruuuuu commented
LGTMいただきありがとうございます！
マージさせていただきます！

2024-01-11 07:39 UTC, merged