自動生成ファイル差分チェック
yumemi-inc/flutter-mobile-project-template pull request #55
Opened 2024-01-12 04:16 UTC by iseruuuuu

## 概要

## レビュー観点

## レビューレベル

- [ ] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [ ] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [ ] 数日以内で見てもらいたい 🐢

## 画像 / 動画

|           Before           |           After            |           Design           |
|:--------------------------:|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> | <img src="" width="300" /> |

## 動作確認手順

## 備考

2024-01-12 06:47 UTC, iseruuuuu commented
@blendthink @warahiko 
お手隙の際にレビューお願いします🙇‍♀️

2024-01-12 06:48 UTC, iseruuuuu commented
@blendthink @warahiko 
お手隙の際にレビューお願いします🙇‍♀️

2024-01-12 08:42 UTC, blendthink reviewed
@iseruuuuu 
少しコメントさせていただきましたので、ご確認お願いします 🙏

2024-01-12 08:42 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +        run: flutter pub get
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
`melos bootstrap` コマンドで `flutter pub get` や `dart pub get` は実行されるため、このステップは削除でお願いします。

2024-01-12 08:42 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +          flutter pub run build_runner build --delete-conflicting-outputs
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`build_runner` に依存しているパッケージやアプリ全て、再生成するように melos スクリプトを作成してそれを実行するようにお願いします 🙏 

FYI:
- https://melos.invertase.dev/configuration/scripts
- https://melos.invertase.dev/filters#--depends-on

2024-01-12 08:42 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +      # https://github.com/actions/checkout
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
このように対象のアクションへのリンクを記載していると、すぐに対象のアクションのオプションとかを調査することができて便利でいいですね✨

2024-01-12 09:50 UTC, warahiko commented on .github/workflows/check-diff.yaml
> +      - name: re-generated code
![nits](https://img.shields.io/badge/review-nits-yellow.svg)
他 step の命名に合わせるとよさそうです
```suggestion
      - name: re-generate code
```

2024-01-12 09:50 UTC, warahiko commented on .github/workflows/check-diff.yaml
> +    types: [ opened, ready_for_review, synchronize ]
![imo](https://img.shields.io/badge/review-imo-orange.svg)
ready_for_review は以前に opened/synchronize で発火したときと差分がない？ので不要そうに思ったんですがどうでしょうか？

2024-01-12 09:50 UTC, warahiko commented on .github/workflows/check-diff.yaml
![nits](https://img.shields.io/badge/review-nits-yellow.svg)
- 細かいですが、step ごとに先頭が大文字か小文字か異なるのが気になりました
- もっと細かいですが、L.1 で code って可算名詞だったかどうか気になりました（これはそんな気にする必要はないかと思います 😅

2024-01-14 23:46 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +      - name: re-generated code
教えていただきありがとうございます！こちらで修正してみました！

2024-01-14 23:49 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
先頭が大文字か小文字かについては統一した方がいいと考え、修正しました。教えていただきありがとうございます！
[b34f9cd](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/b34f9cd266bdc76ca87f920b78c0eefa6afd312e)

2024-01-14 23:56 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
```
もっと細かいですが、L.1 で code って可算名詞だったかどうか気になりました（これはそんな気にする必要はないかと思います 😅
```

この話がいまいちピンときていなくて、詳しく教えていただけると幸いです🙇

2024-01-15 00:13 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +    types: [ opened, ready_for_review, synchronize ]
じっくり考えてみたところ、`opened`と`synchronize`の場合は、走らせなくてもいいなと判断することができましたので、修正してみました。教えていただきありがとうございます！！！
[fe020e8](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/fe020e8fa744640cb43be9145024208a98ce96ef)

2024-01-15 00:17 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +        run: flutter pub get
教えていただきありがとうございます！こちらで修正してみました！
[94efad9](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/94efad9a9b303b4d1b5067753f1d62fd63603491)

2024-01-15 00:38 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +        run: flutter pub get
教えていただきありがとうございます！知らなかったです。。とても勉強になりました！！
こちらで修正しました。
[94efad9](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/94efad9a9b303b4d1b5067753f1d62fd63603491)

2024-01-15 03:01 UTC, warahiko commented on .github/workflows/check-diff.yaml
```yaml
name: Check a generated code is latest
```
に関して、`code` は不可算名詞なので（ https://www.ldoceonline.com/jp/dictionary/code, https://www.ldoceonline.com/jp/dictionary/source-code ）、`a` が不要そう
というコメントでした！
（the が必要になるかはいまいち分からなかった......このプロジェクト内で生成されたコードは特定可能にも思えるけど、毎回異なるわけだし......）

2024-01-15 03:06 UTC, warahiko commented on .github/workflows/check-diff.yaml
https://www.italki.com/ja/post/question-350993
an amount of ~, lines of ~ とかが使われるらしいですね

2024-01-15 03:23 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
意図がわかりました！教えていただきありがとうございます！
そこまで意識していなかったのでとてもありがたいご指摘です！
となると、AIとかに助けてもらいつつ、考えてみたところ以下の感じかなと考えているのですがどうでしょうか・・？
`Check an amount of generated code is the latest`

[6ca00fe](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/6ca00febf5673dd9198578fedab99af457dee08a)

・意味：「生成されたコードの量が最新であることを確認する」
・生成されるコードは使い物によってそれぞれそうなので、`the`ではなく`a`にした方が伝わりやすそうだと思いました！
・「an amount of」も使ってみることにしました！

2024-01-15 03:32 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +    types: [ opened, ready_for_review, synchronize ]
教えていただきありがとうございます！`opened`と`synchronize`の時で良さそうだと考えたので修正してみました！

[561ecda](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/561ecda54609d8e7a60d60a07ea915cadbb106b6)

2024-01-15 03:34 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +          flutter pub run build_runner build --delete-conflicting-outputs
教えていただきありがとうございます！！
こちらで直してみました！
・Commitが細かくなってしまって、レビューしずらいかもしれないと感じたので以下のファイルからご確認いただけると幸いです🙇
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/files

2024-01-15 08:48 UTC, blendthink requested changes
@iseruuuuu 
いくつかコメントさせていただきましたのでご確認お願いします 🙏

2024-01-15 08:48 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +      - name: Run test
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
ここではコードの再生成をしていると思うので、次のような名前が自然そうです。
```suggestion
      - name: Regenerate code
```

2024-01-15 08:48 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +        run: melos run generated_code --no-select
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
コードを再生成するスクリプトなので、 `regenerate_code` が自然そうです。
```suggestion
        run: melos run regenerate_code --no-select
```

2024-01-15 08:48 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +        continue-on-error: true
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
エラーが発生したら問答無用で失敗したほうが適切ですので、削除お願いします 🙏 
（何か認識おかしかったらすみません、、！）

2024-01-15 08:48 UTC, blendthink commented on melos.yaml
> +      flutter: true
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
flutter への依存に関わらず `build_runner` に依存していたら実行されて欲しいので、次のように修正お願いします 🙏 
```suggestion
    exec: dart run build_runner build -d
    packageFilters:
      dependsOn: build_runner
```

2024-01-15 08:48 UTC, blendthink commented on melos.yaml
> +      flutter: true
FYI:


- https://github.com/simolus3/drift/blob/a6834088976f12ea7e000be3b2d00e956b76c422/melos.yaml#L28-L32

2024-01-15 23:32 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +        run: melos run generated_code --no-select
こちらで修正できました！
[4e5d097](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/4e5d097386a936d414d5137422ae73f1c0d5f843)

2024-01-16 00:17 UTC, iseruuuuu commented on melos.yaml
> +      flutter: true
参考になるコードも記載いただきありがとうございます！修正してみました！
[7bc9a04](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/7bc9a048313410a696710bd51fc3b8fbb8a449ca)

2024-01-16 00:24 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +        continue-on-error: true
削除してみました！
確認のため、最新のmainブランチを取り込んだところ、失敗しているのですが、これはcheck-diff.yamlが間違っているのか、最新のmainが間違ってるいるのかどうなのかなと考えています
[675a8dd](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/675a8dd1306c0242d2562de1d12e9eaf5219c4e3)

2024-01-17 03:29 UTC, warahiko commented on .github/workflows/check-diff.yaml
あーすみません、https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55#discussion_r1451890113 に関しては不可算名詞の使われ方の紹介で、ここで使うことの提案ではなかったです 🙏 
自分としては、「量」が正しいかをチェックしているのではなく、中身まで全てチェックしているはずなので、特に形容するものは不要で以下でいいのではと思っています
 `Check generated code is latest`

2024-01-17 03:35 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +        continue-on-error: true
@iseruuuuu 
ご対応ありがとうございます！
失敗しているのは、ワークフローのログを見ればわかると思いますが、自動生成ファイルに差分があるっぽいですね 👀 

https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/7535301221/job/20511064686

![image](https://github.com/yumemi-inc/flutter-mobile-project-template/assets/32213113/5bb501bd-5098-40e6-a9fc-dd5b4768aeb7)

なので、再生成した後で差分がでたものをコミットしてプッシュしていただければいいのかなと思います！

2024-01-17 03:36 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +        continue-on-error: true
指摘した部分については対応していただけているので Resoleve してしまいます！

2024-01-17 03:37 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +      - name: Run test
@iseruuuuu 
ご確認お願いします 🙏 
もし何を言っているのかわからないなどあれば Slack などで気軽にお声掛けいただけると助かります、、！

2024-01-17 03:42 UTC, warahiko commented on .github/workflows/check-diff.yaml
> +        continue-on-error: true
hash に関しては差分がなくても変更される場合があるようですね
https://github.com/rrousselGit/riverpod/issues/2132

2024-01-17 03:48 UTC, warahiko commented on .github/workflows/check-diff.yaml
> +        continue-on-error: true
hash に関しては差分がなくても変更される場合があるようです？

2024-01-17 04:19 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
教えていただきありがとうございます🙇
こちらで修正しました！
[bb2cf79](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/bb2cf7970981a7842b4657199bb2a7ab1f6cb4a4)

2024-01-17 04:21 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +      - name: Run test
リマインドいただきありがとうございます🙇完全に見逃していた気がします。。
こちらで修正できました！
[4ec03c5](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/4ec03c55ec4266532b526eab26ff4e2081edee66)

2024-01-17 06:27 UTC, warahiko commented on .github/workflows/check-diff.yaml
なんどもありがとうございました！

2024-01-17 08:50 UTC, blendthink approved these changes
1点コメントしたものの現状問題はないため Approve させていただきます！
ご対応ありがとうございます！
![LGTM](https://image.lgtmoon.dev/107013)

2024-01-17 08:50 UTC, blendthink commented on .github/workflows/check-diff.yaml
> +          git diff --name-only --exit-code
![next-badge](https://img.shields.io/badge/review-next-blueviolet) 
修正するかどうかはおまかせします、、！（現状、問題はないため）

↓の記事のように改行コードで終わっていることを前提にプログラムが組まれていることが多かったりするので、基本的にファイルの最後の行は改行を入れていただくようにしたほうがメリットありかもしれません。
https://pythonmaniac.com/last-line-newline/#index_id0


また、例えば VS Code の ↓ の拡張機能で自動フォーマットすると
![image](https://github.com/yumemi-inc/flutter-mobile-project-template/assets/32213113/5b292374-2815-4e36-ac4e-de0e6a634839)

↓ のようにフォーマットされます。
![image](https://github.com/yumemi-inc/flutter-mobile-project-template/assets/32213113/4c15fdd9-f2ed-43a1-a0cf-f566bc52b616)

このように、フォーマッターも自動的に最終行に改行がなければ改行を追加することが多くあります。

2024-01-17 09:49 UTC, warahiko reviewed
ご対応ありがとうございました！ LGTM 👍

2024-01-17 09:49 UTC, warahiko commented on melos.yaml
> +      build_runner: ^2.4.7
![ask](https://img.shields.io/badge/review-ask-blue.svg)
ここの依存って必要でしょうか？各パッケージが依存してさえいれば不要なように思ったのですが
ローカルで削除しても問題ないことは確認しています

2024-01-18 00:07 UTC, iseruuuuu commented on .github/workflows/check-diff.yaml
> +          git diff --name-only --exit-code
コメントいただきありがとうございます！ちょうど、Android Stdioの設定で最終行に改行がなければ改行を追加をできるように設定できたのですが、「YAML」の自動フォーマットの設定ができるかどうか探してみようと思います。

とてもわかりやすく記載していただいたので、こちらで修正しました🙇‍♀️
[0b655a2](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/0b655a2515fa5f4366603cb00ee38144d493076d)

2024-01-18 00:14 UTC, iseruuuuu commented on melos.yaml
> +      build_runner: ^2.4.7
こちらの方でも削除したとしても問題なく`dart run build_runner build -d`を使うことができましたので、削除してみました。
教えていただきありがとうございます🙇‍♀️
[2a2d0f5](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/2a2d0f534537a9a635e68508c96ec8db28a7287b)

2024-01-18 02:31 UTC, blendthink commented on melos.yaml
> +      build_runner: ^2.4.7
@iseruuuuu CC: @warahiko 
この指定はプロジェクト内の各パッケージ間で依存関係のバージョンを合わせるために書いているので、記載していたほうがメリットありそうかなと思いますので、修正戻していただければと思います、、！

https://melos.invertase.dev/commands/bootstrap#shared-dependencies

ちなみに、この指定をすることによって、 `melos bootstrap` を実行したときに pubspec.yaml の指定がこの値で上書きされるようになります。

2024-01-18 03:44 UTC, iseruuuuu commented on melos.yaml
> +      build_runner: ^2.4.7
ご指摘いただきありがとうございます🙇‍♀️
`build_runner`は、現状のコードだと`app`だけでしか使われていなさそうでしたが、[こちらのPR](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/65/files)では、`packages`内で`build_runner`を使用し、生成されていることを知り、各パッケージ内で使用されるということを再認識できました。
また、「各パッケージ間で依存関係のバージョンを合わせる」というコメントについても自分の中でとても納得できましたので、修正を戻すことにしました。

改めて自分でしっかりと考えた上でコメントや修正ししていなかったと反省し、努めていこうと思います🙇‍♀️

[438ea55](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/55/commits/438ea5588610c4d33daf40dc9e016714ab64a5a0)

2024-01-18 04:02 UTC, blendthink commented
@iseruuuuu 
最新の main ブランチの取り込みが終わったら確認して Approve しますので、ご対応お願いします 🙏

2024-01-18 04:04 UTC, warahiko commented on melos.yaml
> +      build_runner: ^2.4.7
なるほど、ありがとうございます！
（とすると各 package でのバージョン指定は any などにしたほうがよかったり？）

2024-01-18 04:08 UTC, iseruuuuu commented
@blendthink 
最新を取り込めました！教えていただきありがとうございます🙇‍♀️

2024-01-18 04:20 UTC, iseruuuuu commented on melos.yaml
> +      build_runner: ^2.4.7
ど、どうなんでしょうか。。
`melos.yaml`内でバージョンを指定したということは、apps/app内のpubspec.yaml内にある`build_runner`や`core/packages`[このPRで実装](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/65/files#diff-dcade8db5026cddd2e751aaea9e36cebca3b0afdf4381261e0ce3c7622b6ddcb)記載されているPackageのバージョン指定を指定しなくても、melosの方で指定されているのという認識を持っています。

また、[このPRで実装](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/65/files#diff-dcade8db5026cddd2e751aaea9e36cebca3b0afdf4381261e0ce3c7622b6ddcb)では、`build_runner: ^2.4.8`となっておりすでに２種類のバージョンが存在していることが気になりました👀

ただ、調べてみたところ`any`は非推奨と書いてありました。(ドキュメントをすぐに見つかりそうになかったので記事になっています。すみません。)
https://qiita.com/youmeee/items/035358cf4293d4315b3f

2024-01-18 04:23 UTC, iseruuuuu commented on melos.yaml
> +      build_runner: ^2.4.7
参考になるコメントがありましたので記載させていただきます。

https://zenn.dev/flutteruniv_dev/articles/20231214-054646-flutter-pubspec#comment-00a862299ea295

2024-01-18 04:31 UTC, blendthink approved these changes
![LGTM](https://image.lgtmoon.dev/233991)

2024-01-18 05:29 UTC, iseruuuuu commented on melos.yaml
> +      build_runner: ^2.4.7
@warahiko 
こちらのPRですが、LGTMをいただけたのでマージさせていただきます🙇‍♀️
もし、修正が必要だと分かった場合は、別途でPRを作ろと思います。

2024-01-18 05:29 UTC, merged

2024-01-18 06:15 UTC, warahiko commented on melos.yaml
> +      build_runner: ^2.4.7
>この指定をすることによって、 melos bootstrap を実行したときに pubspec.yaml の指定がこの値で上書きされるようになります

とのことだったので、各パッケージ側で下手にバージョン指定して、「このバージョン指定しているのに動作が違う？？」といった状況にならないように、各パッケージ側では無指定のほうがいい（`build_runner: any # overridden` みたいにするとよりよさそう？）のかな、と思ってのコメントでした！
（このあたりどうですかね？ @blendthink ）

本 PR 自体は問題ないと思います！ 👍

2024-01-18 06:25 UTC, blendthink commented on melos.yaml
> +      build_runner: ^2.4.7
@warahiko 
> とのことだったので、各パッケージ側で下手にバージョン指定して、「このバージョン指定しているのに動作が違う？？」といった状況にならないように、各パッケージ側では無指定のほうがいい（build_runner: any # overridden みたいにするとよりよさそう？）のかな、と思ってのコメントでした！
（このあたりどうですかね？ @blendthink ）

それより全てのバージョンを合わせた方がより適切なので、どちらかといえばすべて melos.yaml に依存関係の記載をして、 CI で `melos bootstrap` を実行して差分が発生するかどうかチェックできたほうがメリット大きいかなと思いました、、！
何か認識おかしかったらすみません 🙏

2024-01-18 06:46 UTC, iseruuuuu commented on melos.yaml
> +      build_runner: ^2.4.7
@blendthink 
よこから失礼します🙇‍♀️
```
すべて melos.yaml に依存関係の記載をして、 CI で melos bootstrap を実行して差分が発生するかどうかチェックする
```

この記載はすでにCIでチェックできているのかが気になりました👀

イメージだと、「CIの中でmelos.yamlのバージョンの指定と各パッケージ側のバージョンの指定が異なっていたら、差分が発生し、失敗させる」という感じに考えているのですが、もし、認識が正しいのであればまだ追記されていない気がしていて、Issuesに追加した方がいいかなと考えております。

2024-01-18 07:03 UTC, iseruuuuu commented on melos.yaml
> +      build_runner: ^2.4.7
僕の中の`git diff --name-only --exit-code`の認識が足りていないと認知できました🙇‍♀️
自動生成されたコードに違いがないのかをチェックするためのCIだと思っていましたが、
```
すべて melos.yaml に依存関係の記載をして、 CI で melos bootstrap を実行して差分が発生するかどうかチェックする
```

この辺りも対応してくれているとなるととてもありがたいですね👍

2024-01-18 07:39 UTC, warahiko commented on melos.yaml
> +      build_runner: ^2.4.7
これ上書きされるってファイルが書き換えられるってことなんですね......