masonの導入
yumemi-inc/flutter-mobile-project-template pull request #62
Opened 2024-01-16 05:07 UTC by Yamasaki-pan961

## 概要
- close: #16 
masonの導入と`cores/`以下のパッケージを作成するbrickの追加をしました。

## レビュー観点

テンプレートに必要な要素が抜けていたり、不要な要素が入っていないか

## レビューレベル

- [ ] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [x] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [x] 今日〜明日中で見てもらいたい 🚶
- [ ] 数日以内で見てもらいたい 🐢

## 動作確認手順

1. [ mason_cliをインストール](https://pub.dev/packages/mason_cli)
2. `mason make core_package_flutter`を実行
3.  `mason make core_package_dart`を実行
4. 生成されたファイルを確認する

## 備考

プロジェクトのSDKバージョンをpackageに自動で反映する機能は作成していません

2024-01-17 03:39 UTC, tatsutakein commented
📝 初回は mason を利用するために以下の作業が必要そう

1. [mason_cliをインストール](https://pub.dev/packages/mason_cli) ※ こちらは動作確認手順に記載のとおり
2. `mason get` を実行で .mason を生成
3. mason-lock.json が絶対パスになっているため Git 上ではロールバック

2024-01-17 04:02 UTC, tatsutakein requested changes
@Yamasaki-pan961 
ご対応いただきありがとうございました！
一点だけ修正をお願いできればと思います 🙏

2024-01-17 04:02 UTC, tatsutakein commented on tools/bricks/core_package_flutter/__brick__/packages/cores/{{package_name.snakeCase()}}/pubspec.yaml
> +  flutter: ">=1.17.0"
<!-- こういう表現もあります -->
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

> プロジェクトのSDKバージョンをpackageに自動で反映する機能は作成していません

こちらは `melos bs` したときに melos.yaml に設定してある値で上書きされるため、あまり気にしなくても良いかもです 🙆

https://github.com/yumemi-inc/flutter-mobile-project-template/blob/da79d3ca27ae77290f7e997075368614e02463d7/melos.yaml#L9-L15

実際に `meson make` した後に `melos bs` したら以下のように変更されていました。

```yaml
environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ^3.16.4
```

2024-01-17 06:13 UTC, Kotaro666-dev commented on tools/bricks/core_package_flutter/__brick__/packages/cores/{{package_name.snakeCase()}}/pubspec.yaml
> +  flutter: ">=1.17.0"
[FYI]

便利ですね！
Android 開発だと buildSrc や Gradle Convention Plugin を使って共通設定を複数のモジュールで共有させるみたいなやり方を簡単にできますね！

> If you want to share dependency versions between your packages in your Melos project, just add the dependencies you wish to share between the packages to your bootstrap config in your melos.yaml file.

https://melos.invertase.dev/~melos-latest/commands/bootstrap#shared-dependencies

2024-01-17 06:38 UTC, Yamasaki-pan961 commented on pubspec.yaml
> +  mason_cli: ^0.1.0-dev.53
細かい指摘ありがとうございます！
melosが入っているため同じように入れてみたのですが、扱いが違うということですか？
melosも`dart pub global activate melos`でセットアップすると認識しております。

2024-01-17 06:52 UTC, Yamasaki-pan961 commented on tools/bricks/core_package_flutter/__brick__/packages/cores/{{package_name.snakeCase()}}/pubspec.yaml
> +  flutter: ">=1.17.0"
補足ありがとうございます！
> こちらは melos bs したときに melos.yaml に設定してある値で上書きされるため、あまり気にしなくても良いかもです 🙆
masonにはhooksがあって、brickの作成前や作成後の処理を記述することができるので`melos bs`させるように設定させるのが良さそうですね！（このPRで対応できるか試してみます）

ただ、yumemi-lintsを使用しているため、`analysis_options.yaml`にバージョンを設定する必要があり、バージョンを取得する処理は必要かも、、？と思いました

```yaml
include: package:yumemi_lints/dart/3.2.3/recommended.yaml
```

2024-01-17 08:24 UTC, tatsutakein requested changes
@Yamasaki-pan961 
ご確認いただけますと幸いです 🙏

2024-01-17 08:24 UTC, tatsutakein commented on pubspec.yaml
> +  mason_cli: ^0.1.0-dev.53
たしかに仰るとおりだと思い、調べ直してみました！
結論からいうと `mason_cli` やはり不要そうで、Melos が少し特殊（サポートが手厚いと言ったほうが良い？）みたいです 💡

Melos 側でバージョン指定が必要なのは、Melos V3 からワークスペース側のバージョンを見に行くようになったためみたいです。
https://melos.invertase.dev/guides/migrations#versioning-of-melos-in-workspaces

実際に `dev_dependencies` から `melos: ^3.4.0` の記述を削除した状態で `melos bs` するとエラーになりました。

※ 逆に `dart pub global deactivate melos` してもエラーになりました

```sh
❯ melos bs
Found a melos.yaml file in "/Users/**/flutter-mobile-project-template" but no local installation of Melos.

From version 3.0.0, the melos package must be installed in a pubspec.yaml file next to the melos.yaml file.

For more information on migrating to version 3.0.0, see: https://melos.invertase.dev/guides/migrations#200-to-300

To migrate at a later time, ensure you have version 2.9.0 or below installed: dart pub global activate melos 2.9.0
```

---

`mason_cli` についてはワークスペースの `dev_dependencies` に `mason_cli: ^0.1.0-dev.53` と追加しても `dart pub global activate mason_cli` でインストールしたグローバル側しかみていないようです。

少し古いバージョンとして `dart pub global activate mason_cli 0.1.0-dev.51` してみてから `mason get` を実行してみたのですが、アップデートできるよ〜〜と言われてしまいました。。

```sh
❯ mason get
✓ Got bricks (69ms)

Update available! 0.1.0-dev.51 → 0.1.0-dev.53
Changelog: https://github.com/felangel/mason/releases/tag/mason_cli-v0.1.0-dev.53
Run mason update to update
```

2024-01-17 08:25 UTC, tatsutakein commented on tools/bricks/core_package_flutter/__brick__/packages/cores/{{package_name.snakeCase()}}/pubspec.yaml
> +  flutter: ">=1.17.0"
あ、たしかに…！！
こちらはやはり必要そうですね 🙇

2024-01-17 08:30 UTC, Yamasaki-pan961 commented on pubspec.yaml
> +  mason_cli: ^0.1.0-dev.53
@tatsutakein 
めちゃくちゃわかりやすくありがとうございます！！
修正いたしました。
afa294097d764a96442d788ca8fc8e6231e2844f

2024-01-17 08:44 UTC, tatsutakein commented on pubspec.yaml
> +  mason_cli: ^0.1.0-dev.53
ご対応いただきありがとうございます〜！
いえいえ、私も解像度が上がったのでとても感謝です 🙌

2024-01-17 10:16 UTC, Yamasaki-pan961 commented
@tatsutakein @blendthink 
追加で以下に対応しました。
- `mason-lock.json`をバージョン管理から除外
- `cores`パッケージを追加するテンプレート作成後に`melos bs`を実行するhooksを実装
- `bricks/`のlint除外を正しく設定

2024-01-17 11:55 UTC, tatsutakein approved these changes
細かい点でいくつかコメントしていますが、大枠 LGTM です！
ご対応いただきありがとうございました 🍀

2024-01-17 11:55 UTC, tatsutakein commented on .gitignore
> +# `mason get`すると内容が絶対パスに書き換わるためバージョン管理しない
<!-- 良い点 -->
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

経緯が書いてあってとても良いと思いました 👌

2024-01-17 11:55 UTC, tatsutakein commented on .gitignore
> +
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

前回気づけず申し訳ないです！
Melos と同じ扱いに見えてしまうので、区分けしても良いかなと思いました 💡

```suggestion

# mason related
.mason
```

2024-01-17 11:55 UTC, tatsutakein commented on tools/bricks/core_package_dart/hooks/pubspec.yaml
> +  mason: ">=0.1.0-dev.52 <0.1.0"
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

せっかくなので最新バージョンで良いかなと思いました。

```suggestion
  mason: ">=0.1.0-dev.53 <0.1.0"
```

2024-01-17 11:55 UTC, tatsutakein commented on tools/bricks/core_package_flutter/hooks/pubspec.yaml
> +  mason: ">=0.1.0-dev.52 <0.1.0"
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

こちらもせっかくなので最新バージョンで良いかなと思いました。

```suggestion
  mason: ">=0.1.0-dev.53 <0.1.0"
```

2024-01-17 11:55 UTC, tatsutakein commented on tools/bricks/core_package_dart/brick.yaml
> +  mason: ">=0.1.0-dev.52 <0.1.0"
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

```suggestion
  mason: ">=0.1.0-dev.53 <0.1.0"
```

2024-01-17 11:55 UTC, tatsutakein commented on tools/bricks/core_package_flutter/brick.yaml
> +  mason: ">=0.1.0-dev.52 <0.1.0"
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

```suggestion
  mason: ">=0.1.0-dev.53 <0.1.0"
```

2024-01-17 12:52 UTC, Yamasaki-pan961 commented on tools/bricks/core_package_dart/hooks/pubspec.yaml
> +  mason: ">=0.1.0-dev.52 <0.1.0"
細かい視点参考になります！（めちゃくちゃありがたいです）

実は`mason`の最新は現状で合ってるようです (https://pub.dev/packages/mason/versions)
`0.1.0-dev.53`は`mason_cli`の方ですね (https://pub.dev/packages/mason_cli)

2024-01-17 12:54 UTC, Yamasaki-pan961 commented on .gitignore
> +
修正しました。
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/62/commits/6130ef69ba5eca6a0bc7f337137c636a668d7c04

2024-01-17 12:57 UTC, Yamasaki-pan961 commented
@tatsutakein 
修正をpushしたためapproveが必要になりました！
再度approveよろしくお願いします

2024-01-18 00:26 UTC, tatsutakein approved these changes
丁寧にご対応いただきありがとうございました！
LGTM です 👍

2024-01-18 01:46 UTC, merged

2024-01-18 04:01 UTC, blendthink reviewed
@Yamasaki-pan961 
すでにマージされてしまいましたが、少しだけコメントしましたので、必要な箇所は Issue 化して別プルリクエストで対応していただければと思います、、！

2024-01-18 04:01 UTC, blendthink commented on tools/bricks/core_package_dart/__brick__/packages/cores/{{package_name.snakeCase()}}/.gitignore
![next-badge](https://img.shields.io/badge/review-next-blueviolet) 
ふと思ったのですが、 flutter や dart のバージョンによってテンプレートが変わってくることを考えると、まず flutter や dart の create コマンドを実行した後に mason のコマンドを実行して必要なもののみ上書きできるようにすると、テンプレートから更新する必要のないファイルを管理せずに済んでよりいいなと思いました。

2024-01-18 04:29 UTC, Yamasaki-pan961 commented on .gitignore
> +.mason
作成しました！
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/68

2024-01-18 04:30 UTC, Yamasaki-pan961 commented on mason.yaml
> +    path: tools/bricks/core_package_dart
issue作成しました！
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/69

2024-01-18 04:34 UTC, Yamasaki-pan961 commented on tools/bricks/core_package_dart/__brick__/packages/cores/{{package_name.snakeCase()}}/.gitignore
issue作成しました
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/70

2024-01-18 04:40 UTC, Yamasaki-pan961 commented
@blendthink 
細かいところまでレビューありがとうございます！