[WIP] アプリアイコン自動生成
yumemi-inc/flutter-mobile-project-template pull request #74
Opened 2024-01-19 03:52 UTC by iseruuuuu

## 概要

## レビュー観点

## レビューレベル

- [ ] Lv1: ぱっとみて違和感がないかチェックして Approve する
- [ ] Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証して Approve する
- [ ] Lv3: 実際に環境で動作確認したうえで Approve する

## レビュー優先度

- [ ] すぐに見てもらいたい ( hotfix など ) 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [ ] 数日以内で見てもらいたい 🐢

## 画像 / 動画

|           Before           |           After            |           Design           |
|:--------------------------:|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> | <img src="" width="300" /> |

## 動作確認手順

## 備考

2024-01-19 07:16 UTC, iseruuuuu commented on apps/app/android/app/build.gradle
> +
こちらを参考にして追記しました。
https://medium.com/flutter-jp/icon-935d637d2da0

2024-01-19 07:16 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +[adaptive icon guid]: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=ja
もっとわかりやすい記載がありましたら、教えていただけると幸いです🙇‍♀️

2024-01-19 07:16 UTC, iseruuuuu commented on apps/app/flutter_launcher_icons-dev.yaml
> +  adaptive_icon_background: '#ffffff'
今回は、`adaptive_icon_background`を画像ではなくカラーコード記載しました

2024-01-19 07:19 UTC, iseruuuuu commented
@tatsutakein @trm11tkr 
お手隙の際にレビューおねがします🙇‍♀️

2024-01-22 07:39 UTC, tatsutakein requested changes
@iseruuuuu 
確認が遅くなってしまい申し訳ないです！
何点かコメント入れたためご確認いただけると幸いです 🙏

2024-01-22 07:39 UTC, tatsutakein commented on apps/app/.gitignore
> +**/android/app/src/main/res/
<!-- 確認 -->
![must-badge](https://img.shields.io/badge/review-must-red.svg)

このプロジェクトとして gitignore はなるべく影響範囲を小さくする方針だと認識しているため、ここの記述は削除して android ディレクトリ配下の gitignore に記載するほうが良いのかもと思いました 💡

```suggestion
```


https://github.com/yumemi-inc/flutter-mobile-project-template/blob/e55d41bfc535ec4ced343d9a85f2cb8f116b3736/apps/app/android/.gitignore#L9-L13

また res ディレクトリを指定してしまうと影響が大きいので、少し絞ってあげた方が良さそうです。

```text
/app/src/main/res/drawable*/ic_launcher*.png
/app/src/main/res/mipmap*/ic_launcher*.png
/app/src/main/res/mipmap*/ic_launcher*.xml
/app/src/main/res/values/colors.xml
```

2024-01-22 07:39 UTC, tatsutakein commented on apps/app/android/app/build.gradle
> +
<!-- こういう表現もあります -->
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Gradle 側で Flavor を定義する方法もあるかなと思いましたが、Flutter アプリ起動時の args が増えることを危惧してのことなのかなと感じ取りました。

動作は確認できたので大丈夫です 🙆

2024-01-22 07:39 UTC, tatsutakein commented on apps/app/assets/launcher_icon/icon_adaptive_dev.png
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

こちらの画像 (stg, prd も含む) は foreground に指定されるものなので、透過画像となっているのが正しい形な気がします 👀
backgound に `#ffffff` を指定しているため気づきにくいですが、 `#000000` など白以外を指定してみると想定とは違う結果になるのがわかると思います 🙆
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=ja

2024-01-22 07:39 UTC, tatsutakein commented on docs/ABOUT_ICON.md
> +| <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/8b62877a-ee02-4aac-8cc2-96beaa7b219a" width="300" /> | <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/fd34
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

いせりゅーさんのレポジトリの画像が参照されているようなので、このプロジェクトのレポジトリの画像に変更すると良さそうです 👍

2024-01-22 07:39 UTC, tatsutakein commented on docs/ABOUT_ICON.md
> +[adaptive icon guid]: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=ja
<!-- 良い点 -->
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

公式リファレンスへのリンクも貼ってあるので、大丈夫だと思いました 🙆

2024-01-22 08:40 UTC, trm11tkr reviewed
画像のご準備ありがとうございます！！
いくつか細かいところをコメントさせていただきましたのでご確認よろしくお願いします！

2024-01-22 08:40 UTC, trm11tkr commented on docs/ABOUT_ICON.md
> +[adaptive icon guid]: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=ja
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
おそらくタイポだと思われるので修正お願いします…!
```suggestion
[adaptive icon guide]: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=ja
```

2024-01-22 08:40 UTC, trm11tkr commented on apps/app/pubspec.yaml
> +flutter_icons:
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
`flutter_launcher_icons `に変更する必要がありそうです
ref: https://github.com/fluttercommunity/flutter_launcher_icons/issues/501

```suggestion
flutter_launcher_icons:
```

2024-01-22 08:40 UTC, trm11tkr commented on docs/ABOUT_ICON.md
> +        -  A color code or background image is required.
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
余分なスペースが含まれてそうです…!

```suggestion
        - A color code or background image is required.
```

2024-01-22 21:56 UTC, iseruuuuu commented on apps/app/.gitignore
> +**/android/app/src/main/res/
確かに絞る意見についてはとても納得できました！教えていただきありがとうございます！
こちらの方で修正してみました！
[d094956](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/d0949561b3a73ca9a1b870ed7a55ef3c1028a411)

2024-01-22 22:02 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +        -  A color code or background image is required.
お手数おかけしました🙇こちらで修正できました！
[a310e9d](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/a310e9dcdb9bd6744ad3400c6ee30456d6d1ea81)

2024-01-22 22:11 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +[adaptive icon guid]: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=ja
こちらで修正できました！
[1f68951](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/1f689515dff598dbd45c889e50cf665fa4bb66e7)

2024-01-22 22:20 UTC, iseruuuuu commented on apps/app/pubspec.yaml
> +flutter_icons:
教えていただきありがとうございます！
てっきり、意図があって`flutter_icons:`のかなと思っていたのですが、ちゃんと議論が行われていたのですね💦
とても勉強になりました🙇

また、こちらの方で修正しました！
[1cef862](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/1cef862c491290c8b9ca690361e0e51fcf224da8)

2024-01-22 23:15 UTC, iseruuuuu commented on apps/app/.gitignore
> +**/android/app/src/main/res/
別の修正で気づいたのですが、教えていただいた記載だと、ignoreされていなかったので、以下の修正をするとちゃんとignoreされていることに気づきましたので、こちらでお伝えさせていただきます🙇
```
**/app/src/main/res/drawable*/ic_launcher*.png
**/app/src/main/res/mipmap*/ic_launcher*.png
**/app/src/main/res/mipmap*/ic_launcher*.xml
**/app/src/main/res/values/colors.xml
```

こちらのCommitで修正しました。
[a98b29a](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/a98b29a1d05740d5d8fbb989a9ebf04d1eb4578d)

2024-01-22 23:16 UTC, iseruuuuu commented on apps/app/assets/launcher_icon/icon_adaptive_dev.png
おっしゃる通りだなと思いました🙇　` #000000`などに変更してみたところ変わっていなかったことに気づいたので、画像の修正をしました。

- 画像の差し替え
[cabea04](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/cabea0434a4df2ffc8375462c6915941fa6daaea)

- 画像の生成
[8d21510](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/8d21510c0156106a93bbaf26fc09d2d38788192f)

2024-01-22 23:18 UTC, iseruuuuu commented on apps/app/assets/launcher_icon/icon_adaptive_dev.png
こちらの修正で#000000にしてみた時のスクリーンショットです！（確認用のため、この後は白に戻しました🙇）
![Screenshot_20240123_075606](https://github.com/yumemi-inc/flutter-mobile-project-template/assets/67954894/109966a0-6944-4589-8a43-bf62300b11ec)

2024-01-22 23:33 UTC, iseruuuuu commented on apps/app/assets/launcher_icon/icon_adaptive_dev.png
### 追記

- Androidのアイコンの画像を透明化したものを`docs/ABOUT_ICON.md`の更新もしました！（透明化しているので分かりづらいかもしれませんが。。💦）

[4497fc1](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/4497fc10a4d1a8ba27c82a525b3284bb2fab7e91)

2024-01-23 02:32 UTC, trm11tkr commented on apps/app/.gitignore
> +**/android/app/src/main/res/
@iseruuuuu 
> 別の修正で気づいたのですが、教えていただいた記載だと、ignoreされていなかったので、以下の修正をするとちゃんとignoreされていることに気づきましたので、こちらでお伝えさせていただきます🙇

記載する `.gitignore` が誤っているためだと思われます…!

https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74#discussion_r1461436545 のコメントで @ tatsutakein さんが掲示してくださっている [/apps/app/android/.gitignore](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/feature/add_app_icon/apps/app/android/.gitignore) が適切かと思いました！

2024-01-23 05:54 UTC, iseruuuuu commented on apps/app/.gitignore
> +**/android/app/src/main/res/
教えていただきありがとうございます🙇
記載場所を間違えておりました。。こちらで修正しました！
[90150ab](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/90150abcaea10d5ea3c26034c7b54b017e35c9fc)

2024-01-24 03:05 UTC, tatsutakein commented on apps/app/.gitignore
> +**/android/app/src/main/res/
ご対応いただきありがとうございます！
問題なさそうに感じました 🙆

2024-01-24 03:07 UTC, tatsutakein commented on apps/app/assets/launcher_icon/icon_adaptive_dev.png
ご対応いただきありがとうございます！
画像の差し替え部分については問題なさそうに感じました 🙆

2024-01-24 03:17 UTC, tatsutakein commented on docs/ABOUT_ICON.md
> +| <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/8b62877a-ee02-4aac-8cc2-96beaa7b219a" width="300" /> | <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/fd34
<!-- 良い点 -->
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74#discussion_r1462554760 で変更いただきありがとうございます 🙌


<!-- 確認 -->
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
ちなみに、まだいせりゅーさんのレポジトリの画像が参照されていそうなのですが、こちらはそういう仕様だったりしますでしょうか…？ 👀
![CleanShot 2024-01-24 at 12 15 30](https://github.com/yumemi-inc/flutter-mobile-project-template/assets/19267812/032c50fb-d1b0-4d7d-ac42-fc3ee3f966af)

2024-01-24 03:19 UTC, tatsutakein reviewed
@iseruuuuu 
ご対応いただきありがとうございます！
[再度一点だけコメントした](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74#discussion_r1464248229) ため、ご確認いただけますと幸いです 🙏

2024-01-24 04:44 UTC, trm11tkr reviewed
修正いただきありがとうございます！
2点コメントさせていただきました！

2024-01-24 04:44 UTC, trm11tkr commented on docs/ABOUT_ICON.md
> +- For a detailed explanation, please check [adaptive icon guid].
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
こちらも修正お願いします…!

```suggestion
- For a detailed explanation, please check [adaptive icon guide].
```

2024-01-24 04:44 UTC, trm11tkr commented on docs/ABOUT_ICON.md
> +        - The size of the icon should be about 0.67 times larger than the size of the image to make it fit better.
> The size of the icon should be about 0.67 times larger than the size of the image to make it fit better.

![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
この情報の参考元を教えていただきたいです！

2024-01-25 00:21 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +| <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/8b62877a-ee02-4aac-8cc2-96beaa7b219a" width="300" /> | <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/fd34
このドキュメントを作成するときに、別のReadMeで作成してその内容をコピペする流れでやっていたため、別のリポジトリの画像から参照されておりました🙇
こちらで修正してみました。
[482068f](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/482068fb05942ca1acabe7482d6763f6725bfdaf)

2024-01-25 00:23 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +- For a detailed explanation, please check [adaptive icon guid].
ごめんなさい💦気づいていませんでした🙇
教えていただきありがとうございます！こちらで修正しました！
[12c5620](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/74/commits/12c56206262ccca9874b841bf80db5ab8ba1ed5e)

2024-01-25 00:24 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +| <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/8b62877a-ee02-4aac-8cc2-96beaa7b219a" width="300" /> | <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/fd34
こちらのコメントですが、今日（1/25）まで気づいておりませんでした🙇リマインドいただきありがとうございます！

2024-01-25 00:39 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +        - The size of the icon should be about 0.67 times larger than the size of the image to make it fit better.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=ja
こちらについてですが、上記のサイトにある文章を参考に考えました。
```
- レイヤのサイズはどちらも 108 x 108 dp にする必要があります。
- アイコンの内側の 72 x 72 dp の部分は、マスクされたビューポート内に表示されます。
4 つの辺それぞれの外側の 18 dp の部分は、パララックスや点滅など、視覚効果を作成する領域として予約されています。
```

主観にはなってしますが、iOSのアイコンのサイズが1024だったのでそれに合わせて、Androidのbackground画像のサイズを1024x1024にした場合、

108:72 = 1:x
108x=72
x=0.6667

という計算から0.67倍ぐらいのサイズがいいと思うと考えています。

この辺りはiOSのサイズを合わせることとできるだけ高画質にすることで生成した時に問題がないようにと思い、サイズの変更したので、ご意見をいただけると幸いです🙇

2024-01-25 04:57 UTC, tatsutakein commented on docs/ABOUT_ICON.md
> +| <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/8b62877a-ee02-4aac-8cc2-96beaa7b219a" width="300" /> | <img src="https://github.com/iseruuuuu/appbar_ui_app/assets/67954894/fd34
ご対応いただきありがとうございました 🙌

2024-01-25 04:57 UTC, tatsutakein approved these changes
LGTM です 👍

2024-01-25 07:08 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +        - The size of the icon should be about 0.67 times larger than the size of the image to make it fit better.
タッツーさんからLGTMをいただけたので、マージさせていただきますが、この議論については引き続きできればなと思っております🙇

2024-01-25 07:22 UTC, iseruuuuu commented on docs/ABOUT_ICON.md
> +        - The size of the icon should be about 0.67 times larger than the size of the image to make it fit better.
タッツーさんからLGTMをいただけたので、マージさせていただきますが、こちらの議論は引き続きできればなと思っております🙇

2024-01-25 07:28 UTC, merged